### ISSUE TITLE
[Bug] Script works but visual bug with Deezer's skip button on slider

### ISSUE THREAD

**Issue by CHJ85** [TheNolle/TheNolle#1]
Hi there.  I know your Deezer premium script has been archived and will probably not see an update.
The script works fine. However, there's one minor issue with the slider. Skipping in songs is disabled using `disabled=""`.
Do you think you could update the script with a fix for that?
This only happens on the search page. Not on the album/single or artist page. So it's not a huge deal, but can be a bit annoying.

**Comment by TheNolle** [comment]
I'm sorry, i've stopped working on it, althought, you can create a fork of it and fix the issue if you want to
If you don't know how, then i think i'll have to fix this myself, let me know on my discord about it: https://TheNolle.com/Discord
Cause I don't check the messages here

**Comment by TheNolle** [comment]
Well, I've just tested out and it seems to work correctly, make you you reinstall this script <a href="https://github.com/TheNolles-Studios-Abandonned/Deezer-Premium">Deezer Premium</a>, Everything works for me so, if you still have the error you are speaking about, let me know

Be informed that it works only with the web app of deezer, where the extension TamperMonkey can work

**Comment by TheNolle** [comment]
Seems like you don't have the issue anymore, or you are just inactive, i'll close this issue, if you still have the problem, I recommend you to dm me on discord/join my discord

**Comment by CHJ85** [comment]
Yea sorry for not getting back to you. The script stopped working completely. I bet they've made changes to the  site again.
